name 'puppet_stumpwm'
version '0.0.1'
summary 'A puppet module to install and setup the stumpwm on a linux box'
description "This module aims to install stumpwm and create the xsessions/stumpwm.desktop file."
license 'GPLv3'
author 'Antoine R. Dumont'
source 'https://github.com/ardumont/puppet-stumpwm'
project_page 'https://github.com/ardumont/puppet-stumpwm'
