class packages () {

  # fill the packages here
  package {["emacs",
            "git",
            "gitk",
            "tmux",
            "wget",
            "gitk",
            "gitk",
            "chromium-browser",
            "localepurge",
            "deborphan",
            "language-pack-en",
            "language-pack-fr",
            "gparted",
            "stalonetray",
            "",
            "sweethome3d",
            "inotify-tools",
            "ruby",
            "curl",
            "yajl-tools",
            "openssh-server",
            "sysvbanner",
            "most",
            "graphviz",
            "audacious",
            "audacious-plugins",
            "gnuplot",
            "vim",
            "latex",
            "latex-beamer",
            "texlive-latex-extra",
            "texlive-fonts-recommended",
            "ttf-marvosym",
            "nautilus-dropbox",
            "gtalk",
            "meld",
            "dstat",
            "htop",
            "zip",
            "unzip",
            "rar",
            "unrar",
            "p7zip",
            "p7zip-rar",
            "xclip",
            "gpointing-device-settings"]:
    ensure => present,
  }
}
