name 'network-setup'
version '0.0.1'
summary 'A network module to setup the network files once the vms are started'
description "This module aims to install the /etc/hosts and /etc/resolv.conf files."
license 'GPLv3'
author 'Antoine R. Dumont'
source 'https://github.com/ardumont/puppet-setup'
project_page 'https://github.com/ardumont/puppet-setup'
